### ISSUE TITLE
Push SNAPSHOT's to maven central

### ISSUE THREAD

**Issue by berndruecker** [camunda-cloud/zeebe-process-test#118]
Looks like currently the SNAPSHOT's are not yet automatically pushed to Maven Central, making all latest changes much harder to use/test

**Comment by pihme** [comment]
If you refer to this run: https://github.com/camunda-cloud/zeebe-process-test/actions/runs/1607679378
That one had a test failure and the aborted. Most likely related to flakiness of tests #119

**Comment by remcowesterhoud** [comment]
This issue is most likely fixed with the fixes that improve the test stability. Therefore, I'm closing this for now.
