### ISSUE TITLE
Set up licensing

### ISSUE THREAD

**Issue by remcowesterhoud** [camunda-cloud/zeebe-process-test#171]
**Description**

We need to properly license our code. None of this project is part of the core-business. Therefore the project can be licensed under the regular Apache 2 license.
One exception is the in memory engine. This module depends on the zeebe broker, which is part of the core-business. This means that the engine module must follow the same license as the zeebe broker.

**What we need to do:**
1. Create a license folder like in zeebe (https://github.com/camunda-cloud/zeebe/tree/main/licenses) containing the apache license and the zeebe license.
2. Add a section to the README and the Contribution Guide specifying that all modules are licensed under Apache 2, except for the engine which is licensed under the Zeebe license.
3. Remove the LICENSE file

**Comment by pihme** [comment]
What about adding license/copyright headers to all source files and checking that these are there?

**Comment by remcowesterhoud** [comment]
Another note: License gets added to the flatten pom. This is always Apache 2.0. For `engine`, `engine-agent` and `extension` these need to be changed to the Zeebe license.
