### ISSUE TITLE
Review compile time dependencies

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe-process-test#174]
**Description**

Right now, adding the project as a dependency has the downside of including Log4J as the SLF4J implementation. If your project already includes it, then you get conflicts and it's unclear which implementation will get used. So the implementation in this project should be a test scoped dependency.

I think there may also be other dependencies which should not be compile time, but I imagine you have a better than me on that account. Happy to discuss this f2f.

NOTE: I think this may go away once we containerize the engine, but as we may end up supporting embedding the engine anyway, I think it's worth doing regardless.

NOTE: I would also propose using just `slf4-simple` as an implementation if it's only for testing, no need to bring in log4j.

**Comment by zambrovski** [comment]
I can't agree with `slf4-simple` as a hard requirement. If you take a typical SpringBoot application, you ill already have other slf4j implementation on your classpath (log-back or log4j). I believe it is better to provide no logging implementation and add a side not for everyone who is not using is in a project with an already provided implementation.

**Comment by npepinpe** [comment]
Let me clarify :sweat_smile: I meant, I would propose slf4j-simple only for tests, so it would be a test scoped dependency, and there would not be a compile time slf4j implementation.

**Comment by zambrovski** [comment]
Ah! Then full agree. Change the scope of slf4j-simple to test!

**Comment by berndruecker** [comment]
@zambrovski forced me to 👍 :-)
