### ISSUE TITLE
Using stable branches

### ISSUE THREAD

**Issue by npepinpe** [camunda-cloud/zeebe-process-test#181]
**Description**

As releasing this project will soon be part of our wider release process, we should adopt the same idea of using stable branches to build patch releases more easily.

**Comment by remcowesterhoud** [comment]
Thanks for creating the issue! Stable branches will start with release 1.4. This is already written down in the release process, so I'll close this issue.

**Comment by npepinpe** [comment]
Cool, thanks! This came up because I wanted to do another 1.3 release now, but I guess it's not that big a deal for now :smile:
